apiVersion: v1
data:
  data: '[{"authorizedClientCerts": ["flowsnake_master_iot_test"], "authorizedLdapGroups":
    ["Flowsnake_Ops_Platform"], "namespace": "flowsnake"}, {"authorizedClientCerts":
    ["retail-cre.cre-control-plane-ccp-func", "retail-cre.cre-control-plane-ccp-perf",
    "retail-cre.cre-control-plane-ccp-dev"], "authorizedLdapGroups": ["CRE_AD"], "namespace":
    "retail-cre"}, {"authorizedClientCerts": ["iot.provisioning", "iot.provisioning-ftest",
    "iot.provisioning-provisioningtest"], "authorizedLdapGroups": ["IoT-RM-Flowsnake"],
    "namespace": "iot"}, {"authorizedClientCerts": ["wave-elt.datapool", "wave-elt.datapool-test1",
    "wave-elt.datapool-test2", "wave-elt.datapool-steelthread"], "authorizedLdapGroups":
    ["Analytics-DataPool"], "namespace": "wave-elt"}]'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: auth-namespaces
  namespace: flowsnake
