apiVersion: v1
data:
  spec.jaysawn: '{"env": [{"name": "SETTINGS_PATH", "value": "-.-.prd.-."}, {"name":
    "SETTINGS_SUPERPOD", "value": "-"}, {"name": "SFDC_SETTINGS_PATH", "value": "-.-.prd.-."},
    {"name": "SFDC_SETTINGS_SUPERPOD", "value": "-"}, {"name": "JVM_HEAP_MAX", "value":
    "1024M"}], "image": "ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicelibs/sherpa-envoy:1.0.5",
    "imagePullPolicy": "IfNotPresent", "livenessProbe": {"exec": {"command": ["./bin/is-alive"]},
    "failureThreshold": 3, "initialDelaySeconds": 120, "periodSeconds": 5, "successThreshold":
    1, "timeoutSeconds": 1}, "name": "<replaced>", "readinessProbe": {"exec": {"command":
    ["./bin/is-ready"]}, "failureThreshold": 3, "initialDelaySeconds": 110, "periodSeconds":
    5, "successThreshold": 1, "timeoutSeconds": 1}, "resources": {"limits": {"cpu":
    "2.0", "memory": "4Gi"}, "requests": {"cpu": "2.0", "memory": "4Gi"}}, "terminationMessagePath":
    "/dev/termination-log", "terminationMessagePolicy": "File"}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: service-mesh-container-spec
  namespace: flowsnake
