apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    cloud: storage
    name: dummy-storageservice-deployment
    sam.data.sfdc.net/owner: storage
    team: storage-foundation
  name: dummy-storageservice
  namespace: storage
spec:
  replicas: 0
  template:
    metadata:
      labels:
        cloud: storage
        name: dummy-storageservice-deployment
        team: storage-foundation
    spec:
      containers:
      - image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/storagecloud/configwatcher:base-0000437-311530ce
        name: configwatcher
      - image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/storagecloud/ceph-daemon:10.2.7-0000062-6d863283
        name: cephdaemon
      - image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/storagecloud/bookie:base-0000089-39319751
        name: sfstore-bookie
      - image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/storagecloud/loginitcontainer:base-0000437-311530ce
        name: loginit
