apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "storage_samcomputedev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamcomputedev1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p04-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samcomputedev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamcomputedev1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p04-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samcomputedev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamcomputedev2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "bb38-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samcomputedev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamcomputedev2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "bb38-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samcomputedev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamcomputedev3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "s03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samkubeapidev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samkubeapi",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamkubeapidev1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p32-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samkubeapidev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samkubeapi",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamkubeapidev2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "q09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samkubeapidev",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samkubeapi",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagesamkubeapidev3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "s03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "storage_samcomputedev2",
          "controlestate": "prd-sam_storagedev",
          "devicerole": "samcompute",
          "estate": "prd-sam_storagedev",
          "hostname": "shared0-storagetwosamcomputedev1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k22-45",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
