apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: watchdog-deployment
    sam.data.sfdc.net/owner: sam
  name: watchdog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watchdog-deployment
  template:
    metadata:
      labels:
        apptype: monitoring
        name: watchdog-deployment
        sam.data.sfdc.net/owner: sam
      namespace: sam-system
    spec:
      containers:
      - command:
        - /sam/watchdog
        - -role=DEPLOYMENT
        - -watchdogFrequency=10s
        - -alertThreshold=1h
        - -watchDogKind=Deployment
        - -emailFrequency=10000h
        - -funnelEndpoint=ajna0-funnel1-0-cdu.data.sfdc.net:80
        - --config=/config/watchdog.json
        - --hostsConfigFile=/sfdchosts/hosts.json
        - -timeout=2s
        env:
        - name: KUBECONFIG
          value: /kubeconfig/kubeconfig-platform
        image: ops0-artifactrepo1-0-cdu.data.sfdc.net/dva/sam/hypersam:2814-bdc65579e01f6a124d636d2cb837cb7e6d4afd6f
        name: watchdog-deployment
        volumeMounts:
        - mountPath: /etc/pki_service
          name: maddog-certs
        - mountPath: /kubeconfig
          name: kubeconfig
        - mountPath: /sfdchosts
          name: sfdchosts
        - mountPath: /data/certs
          name: certs
        - mountPath: /config
          name: config
      hostNetwork: true
      nodeSelector:
        pool: cdu-sam
      volumes:
      - hostPath:
          path: /etc/pki_service
        name: maddog-certs
      - hostPath:
          path: /etc/kubernetes
        name: kubeconfig
      - configMap:
          name: sfdchosts
        name: sfdchosts
      - hostPath:
          path: /data/certs
        name: certs
      - configMap:
          name: watchdog
        name: config
