apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: nginx-ingress-lb
    name: nginx-ingress-lb
  name: nginx-ingress-controller
  namespace: flowsnake
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        flowsnakeOwner: dva-transform
        flowsnakeRole: NginxIngressController
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      containers:
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --sync-period=30s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: /etc/kubernetes/kubeconfig
        image: ops0-artifactrepo1-0-syd.data.sfdc.net/dva/flowsnake-ingress-controller-nginx:662
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - reply=$(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:80/healthz);
              if [ "$reply" -lt 200 -o "$reply" -ge 400 ]; then exit 1; fi; ps -o
              comm,etime | grep nginx-ingress | grep -cE '[1-9]-[0-9]' | grep -q 0
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: nginx-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: flowsnake-tls-secret
          readOnly: true
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/pki_service/ca
          name: k8s-certificate-authority
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/certificates
          name: k8s-client-certificate
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/keys
          name: k8s-client-key
          readOnly: true
      - args:
        - -endpoint
        - flowsnake/api:DATACENTER_ALLENV:443:flowsnake-syd.data.sfdc.net
        - -path
        - -.-.syd.-.flowsnake
        - -spod
        - NONE
        image: ops0-artifactrepo1-0-syd.data.sfdc.net/sfci/servicelibs/beacon:853c4db9f14805018be6f5e7607ffe65b5648822
        name: beacon
      terminationGracePeriodSeconds: 60
      volumes:
      - name: flowsnake-tls-secret
        secret:
          secretName: flowsnake-tls
      - hostPath:
          path: /etc/kubernetes/kubeconfig
        name: kubeconfig
      - hostPath:
          path: /etc/pki_service/ca
        name: k8s-certificate-authority
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/certificates
        name: k8s-client-certificate
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/keys
        name: k8s-client-key
