apiVersion: v1
data:
  proxyconfiguration.json: |-
    {
      "proxyconfigs": [
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-nginx-config-b"
        },
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-hsm-nginx"
        }
      ]
    }
  proxyvipmapping.json: |-
    {
      "proxyvipmappings": [
        {
          "proxyname": "slb-hsm-nginx",
          "vips": [
            "login-cloudforce-dfw.slb.sfdc.net",
            "gs0-bofa-dfw.slb.sfdc.net",
            "org-cce2e-cs3-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs7-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs9-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs10-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs11-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs12-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs13-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs19-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs20-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs21-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs23-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs25-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs26-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs30-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs50-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs51-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs52-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs53-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs54-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs59-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs60-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs61-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs62-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs63-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs68-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs69-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs70-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs71-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs90-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs91-slb-dfw.slb.sfdc.net",
            "org-cce2e-cs999-slb-dfw.slb.sfdc.net",
            "org-orgcerttest-cs997-slb-dfw.slb.sfdc.net",
            "org-cce2e-na47-slb-dfw.slb.sfdc.net",
            "slb-canary-hsm.sam-system.dfw-sam.dfw.slb.sfdc.net"
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-proxy-configuration
  namespace: sam-system
