apiVersion: v1
data:
  data: '[{"authorizedClientCerts": ["flowsnake_master"], "authorizedLdapGroups":
    ["Flowsnake_Ops_Platform"], "namespace": "flowsnake"}, {"authorizedClientCerts":
    [ ], "authorizedLdapGroups": ["alerting_flowsnake"], "namespace": "alerting_snmp"},
    {"authorizedClientCerts": [ ], "authorizedLdapGroups": ["security-analytics"],
    "namespace": "sec-einstein-deepsea"}, {"authorizedClientCerts": [ ], "authorizedLdapGroups":
    ["collection_flowsnake"], "namespace": "collection_device_data_mon"}, {"authorizedClientCerts":
    [ ], "authorizedLdapGroups": ["search_dlc"], "namespace": "search_dlc"}, {"authorizedClientCerts":
    ["universal-search.universal-search"], "authorizedLdapGroups": ["universal-search"],
    "namespace": "universal-search"}, {"authorizedClientCerts": [ ], "authorizedLdapGroups":
    ["Sayonara-Flowsnake"], "namespace": "sayonara-applogs"}, {"authorizedClientCerts":
    [ ], "authorizedLdapGroups": ["edge_intelligence"], "namespace": "edge_intelligence"},
    {"authorizedClientCerts": [ ], "authorizedLdapGroups": ["dbvisibility"], "namespace":
    "database-heimdall"}, {"authorizedClientCerts": ["flowsnake_test"], "authorizedLdapGroups":
    ["Flowsnake_Platform"], "namespace": "flowsnake_test"}, {"authorizedClientCerts":
    [ ], "authorizedLdapGroups": ["Analytics Service Ownership"], "namespace": "einstein_analytics_discovery_monitoring"},
    {"authorizedClientCerts": ["wave-elt.datapool"], "authorizedLdapGroups": ["Analytics-DataPool"],
    "namespace": "wave-elt"}, {"authorizedClientCerts": [ ], "authorizedLdapGroups":
    ["Analytics-DataPool"], "namespace": "wave-discovery"}, {"authorizedClientCerts":
    [ ], "authorizedLdapGroups": ["lpanalytics_flowsnake"], "namespace": "lp-analytics"}]'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: auth-namespaces
  namespace: flowsnake
