apiVersion: v1
data:
  kubeconfig: /etc/kubernetes/kubeconfig
  name: yul-flowsnake_prod
  registry: ops0-artifactrepo1-0-yul.data.sfdc.net
  strata_registry: ops0-artifactrepo1-0-yul.data.sfdc.net/dva
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fleet-config
  namespace: default
