apiVersion: v1
data:
  kubeconfig: /etc/kubernetes/kubeconfig
  name: par-flowsnake_prod
  registry: ops0-artifactrepo1-0-par.data.sfdc.net
  strata_registry: ops0-artifactrepo1-0-par.data.sfdc.net/dva
  vip: flowsnake-par.data.sfdc.net
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fleet-config
  namespace: flowsnake
