apiVersion: v1
data:
  spec.jaysawn: '{"args": ["/sam/madkub-client", "--madkub-endpoint", "https://10.254.208.254:32007",
    "--maddog-endpoint", "https://all.pkicontroller.pki.blank.par.prod.non-estates.sfdcsd.net:8443",
    "--maddog-server-ca", "/etc/pki_service/ca/security-ca.pem", "--madkub-server-ca",
    "/etc/pki_service/ca/cacerts.pem", "--token-folder", "/tokens", "--kingdom", "par",
    "--superpod", "None", "--estate", "par-flowsnake_prod", "--cert-folders", "usercerts:/certs",
    "--cert-folders", "servercerts:/servercerts", "--ca-folder", "/etc/pki_service/ca",
    "--funnel-endpoint", "http://ajna0-funnel1-0-par.data.sfdc.net:80"], "env": [{"name":
    "MADKUB_NODENAME", "valueFrom": {"fieldRef": {"apiVersion": "v1", "fieldPath":
    "spec.nodeName"}}}, {"name": "MADKUB_NAME", "valueFrom": {"fieldRef": {"apiVersion":
    "v1", "fieldPath": "metadata.name"}}}, {"name": "MADKUB_NAMESPACE", "valueFrom":
    {"fieldRef": {"apiVersion": "v1", "fieldPath": "metadata.namespace"}}}], "image":
    "ops0-artifactrepo1-0-par.data.sfdc.net/tnrp/sam/madkub:1.0.0-0000084-9f4a6ca6",
    "name": "<replaced>", "resources": {"limits": {"cpu": "1.0", "memory": "1Gi"},
    "requests": {"cpu": "1m", "memory": "1Mi"}}, "securityContext": {"runAsNonRoot":
    true, "runAsUser": 7447}, "volumeMounts": [{"mountPath": "/certs", "name": "datacerts"},
    {"mountPath": "/servercerts", "name": "servercerts"}, {"mountPath": "/tokens",
    "name": "tokens"}, {"mountPath": "/etc/pki_service/ca", "name": "certificate-authority",
    "readOnly": true}, {"mountPath": "/etc/pki_service/platform/platform-client/certificates",
    "name": "client-certificate", "readOnly": true}, {"mountPath": "/etc/pki_service/platform/platform-client/keys",
    "name": "client-key", "readOnly": true}]}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: madkub-container-spec
  namespace: flowsnake
