apiVersion: v1
data:
  samcontrol.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/data/certs/hostcert.crt",
      "checkImageExistsFlag": false,
      "debug": true,
      "deletionEnabled": false,
      "deletionPercentageThreshold": 20,
      "dockerregistry": "ops0-artifactrepo1-0-yul.data.sfdc.net",
      "enableMaddog": true,
      "httpsDisableCertsCheck": true,
      "imageCheckV2": true,
      "k4aInitContainerImage": "ops0-artifactrepo1-0-yul.data.sfdc.net/tnrp/sam/hypersam:sam-0001800-1972769a",
      "k8sapiserver": "",
      "keyFile": "/data/certs/hostcert.key",
      "maddogMaddogEndpoint": "https://all.pkicontroller.pki.blank.yul.prod.non-estates.sfdcsd.net:8443",
      "maddogMadkubImage": "ops0-artifactrepo1-0-yul.data.sfdc.net/tnrp/sam/madkub:1.0.0-0000061-74e4a7b6",
      "slbConfigInAnnotations": false,
      "slbConfigInLabels": false,
      "statefulAppEnabled": false,
      "tlsEnabled": true,
      "volPermissionInitContainerImage": "ops0-artifactrepo1-0-yul.data.sfdc.net/tnrp/sam/hypersam:sam-1ebeb0ac-657"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: samcontrol
  namespace: sam-system
