apiVersion: v1
data:
  slb-reserved-ips-hnd.json: |-
    {
      "cre-api-lb.retail-cre.par-sam.hnd.slb.sfdc.net": "10.213.100.14",
      "cre-control-plane-lb.retail-cre.hnd-sam.hnd.slb.sfdc.net": "10.213.100.136",
      "cre-sp-lb.retail-cre.hnd-sam.hnd.slb.sfdc.net": "10.213.100.137",
      "dfs-production-lb.retail-dfs.hnd-sam.hnd.slb.sfdc.net": "10.213.100.138",
      "hub-persistence-lb.retail-rsui.hnd-sam.hnd.slb.sfdc.net": "10.213.100.141",
      "metadata-service-lb.retail-mds.hnd-sam.hnd.slb.sfdc.net": "10.213.100.140",
      "rsui-production-hnd-lb.retail-rsui.hnd-sam.hnd.slb.sfdc.net": "161.71.144.14",
      "rsui-production-hnd-test-lb.retail-rsui.hnd-sam.hnd.slb.sfdc.net": "161.71.144.15",
      "rsui-service-hnd-lb.retail-rsui.hnd-sam.hnd.slb.sfdc.net": "10.213.100.139",
      "slb-canary-proxy-http-ext.sam-system.hnd-sam.hnd.slb.sfdc.net": "161.71.144.5",
      "sledge-hnd.slb.sfdc.net": "161.71.144.13"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-reserved-ips
  namespace: sam-system
