apiVersion: v1
data:
  tcpdumpcommand.json: |-
    {
      "tcpdumpcommands": [
        {
          "command": "-i eth0",
          "duration": "1m",
          "packetcapture": false
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-tcpdump-ipvs-tcpdump
  namespace: sam-system
