apiVersion: v1
data:
  host-repair-aggregator.json: |-
    {
      "crdNamespace": "sam-system",
      "crdPollFrequency": "5m",
      "crdPushFrequency": "5m",
      "dbHostname": "mysql-inmem-read.sam-system.prd-sam.prd.slb.sfdc.net",
      "dbPasswordFile": "/var/mysqlPwd/host-repair-agg",
      "dbUsername": "host-repair-agg",
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "k8sCeListFromDB": [
        "prd-samtest"
      ],
      "k8sFromDB": true,
      "k8sResourceDbName": "sam_kube_resource",
      "k8sResourceTableName": "k8s_resource",
      "nodeOfflineAfterTime": "60m",
      "signals": [
        "filesystemChecker",
        "maddogCertChecker",
        "kubeletChecker"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: host-repair-aggregator
  namespace: sam-system
