apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    routing.mesh.sfdc.net/enabled: "true"
    sidecar.istio.io/inject: "true"
  name: route-update-service
  namespace: service-mesh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: route-update-service
  template:
    metadata:
      annotations:
        madkub.sam.sfdc.net/allcerts: |-
          {
           "certreqs": [
            {
             "cert-type": "client",
             "kingdom": "prd",
             "name": "tls-client-cert",
             "role": "route-update-service.service-mesh"
            },
            {
             "cert-type": "server",
             "kingdom": "prd",
             "name": "tls-server-cert",
             "role": "route-update-service.service-mesh",
             "san": [
              "route-update-service",
              "route-update-service.service-mesh",
              "route-update-service.service-mesh.sfdc-role",
              "route-update-service.service-mesh.svc",
              "route-update-service.service-mesh.svc.prd-samtest.prd.sam.sfdc.net"
             ]
            }
           ]
          }
        routing.mesh.sfdc.net/enabled: "true"
        sidecar.istio.io/inject: "true"
      labels:
        app: route-update-service
        cluster: prd-samtest
        sam_function: route-update-service
        settings_path: mesh.-.prd.-.route-update-service
    spec:
      containers:
      - args:
        - -p
        - "7443"
        - --funnel-address
        - ajnafunneldirecttls.funnel.svc.mesh.sfdc.net:7442
        env:
        - name: ESTATE
          value: prd-samtest
        - name: SETTINGS_SUPERPOD
          value: '-'
        - name: SETTINGS_PATH
          value: mesh.-.prd.-.route-update-service
        - name: FAKE_RESTART_VAR
          value: "2"
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicemesh/servicemesh/route-update-service:21b05ffaaf87dd1f7da1f5ea8f130138a89e50bc
        imagePullPolicy: IfNotPresent
        name: route-update-service
        ports:
        - containerPort: 7443
          name: grpc-svc
        readinessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
            sam.sfdc.net/ip-address: "1"
          requests:
            cpu: 100m
            memory: 128Mi
            sam.sfdc.net/ip-address: "1"
        volumeMounts:
        - mountPath: /etc/pki_service
          name: maddog-certs
      - args:
        - /sam/madkub-client
        - --madkub-endpoint=https://10.254.208.254:32007
        - --maddog-endpoint=https://all.pkicontroller.pki.blank.prd.prod.non-estates.sfdcsd.net:8443
        - --maddog-server-ca=/maddog-certs/ca/security-ca.pem
        - --madkub-server-ca=/maddog-certs/ca/cacerts.pem
        - --cert-folders=tls-client-cert:/tls-client-cert/
        - --cert-folders=tls-server-cert:/tls-server-cert/
        - --token-folder=/tokens/
        - --ca-folder=/maddog-certs/ca
        - --refresher
        - --run-init-for-refresher-mode
        - "false"
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/madkub:1.0.0-0000084-9f4a6ca6
        imagePullPolicy: IfNotPresent
        name: madkub-refresher
        resources: {}
        volumeMounts:
        - mountPath: /tls-client-cert
          name: tls-client-cert
        - mountPath: /tls-server-cert
          name: tls-server-cert
        - mountPath: /maddog-certs/
          name: maddog-certs
        - mountPath: /tokens
          name: tokens
      initContainers:
      - args:
        - /sam/madkub-client
        - --madkub-endpoint=https://10.254.208.254:32007
        - --maddog-endpoint=https://all.pkicontroller.pki.blank.prd.prod.non-estates.sfdcsd.net:8443
        - --maddog-server-ca=/maddog-certs/ca/security-ca.pem
        - --madkub-server-ca=/maddog-certs/ca/cacerts.pem
        - --cert-folders=tls-client-cert:/tls-client-cert/
        - --cert-folders=tls-server-cert:/tls-server-cert/
        - --token-folder=/tokens/
        - --ca-folder=/maddog-certs/ca
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/madkub:1.0.0-0000084-9f4a6ca6
        imagePullPolicy: IfNotPresent
        name: madkub-init
        volumeMounts:
        - mountPath: /tls-client-cert
          name: tls-client-cert
        - mountPath: /tls-server-cert
          name: tls-server-cert
        - mountPath: /maddog-certs/
          name: maddog-certs
        - mountPath: /tokens
          name: tokens
      - command:
        - bash
        - -c
        - |
          set -ex
          chmod 775 -R /tls-client-cert && chown -R 7447:7447 /tls-client-cert
          chmod 775 -R /tls-server-cert && chown -R 7447:7447 /tls-server-cert
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-c07d4afb-673
        imagePullPolicy: Always
        name: permissionsetterinitcontainer
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /tls-client-cert
          name: tls-client-cert
        - mountPath: /tls-server-cert
          name: tls-server-cert
      nodeSelector:
        pool: prd-samtest
      serviceAccountName: route-update-service-service-account
      volumes:
      - hostPath:
          path: /etc/pki_service
        name: maddog-certs
      - emptyDir:
          medium: Memory
        name: tls-client-cert
      - emptyDir:
          medium: Memory
        name: tls-server-cert
      - emptyDir:
          medium: Memory
        name: tokens
