apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "samtest_compute",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestcompute1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k11-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtest_compute",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestcompute1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v34-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtest_compute",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestcompute2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "w31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtest_kube_api",
          "controlestate": "prd-samtest",
          "devicerole": "samkubeapi",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestkubeapi1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtest_kube_api",
          "controlestate": "prd-samtest",
          "devicerole": "samkubeapi",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestkubeapi2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "m38-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtest_kube_api",
          "controlestate": "prd-samtest",
          "devicerole": "samkubeapi",
          "estate": "prd-samtest",
          "hostname": "shared0-samtestkubeapi3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtestpool",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtestpool",
          "hostname": "shared0-samtestpool1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "f35-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtestpool",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtestpool",
          "hostname": "shared0-samtestpool2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "j07-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtestpool",
          "controlestate": "prd-samtest",
          "devicerole": "samcompute",
          "estate": "prd-samtestpool",
          "hostname": "shared0-samtestpool3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k07-45",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
