apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sherpa-injector
  name: sherpa-injector
  namespace: service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sherpa-injector
      sherpa-injector.service-mesh/inject: disabled
  template:
    metadata:
      annotations:
        madkub.sam.sfdc.net/allcerts: |-
          {
           "certreqs": [
            {
             "cert-type": "server",
             "kingdom": "prd",
             "name": "cert1",
             "role": "sherpa-injector",
             "san": [
              "sherpa-injector",
              "sherpa-injector.service-mesh",
              "sherpa-injector.service-mesh.svc",
              "sherpa-injector.service-mesh.svc.prd-samtest.prd.sam.sfdc.net"
             ]
            },
            {
             "cert-type": "client",
             "kingdom": "prd",
             "name": "cert2",
             "role": "sherpa-injector",
             "san": [
              "sherpa-injector",
              "sherpa-injector.service-mesh",
              "sherpa-injector.service-mesh.svc",
              "sherpa-injector.service-mesh.svc.prd-samtest.prd.sam.sfdc.net"
             ]
            }
           ]
          }
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: sherpa-injector
        sherpa-injector.service-mesh/inject: disabled
    spec:
      containers:
      - args:
        - --template=sherpa-container.yaml.template
        - --image=ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicelibs/sherpa-envoy:6c67c98234e9f47f2ff9bb9c5c90acc6ac390be7
        - --log-level=debug
        - --port=17442
        - --cert=/server-certs/server/certificates/server.pem
        - --key=/server-certs/server/keys/server-key.pem
        - --canary-image=ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicelibs/sherpa-envoy:6c67c98234e9f47f2ff9bb9c5c90acc6ac390be7
        env:
        - name: SFDC_ENVIRONMENT
          value: mesh
        - name: SETTINGS_SERVICENAME
          value: sherpa-injector
        - name: FUNCTION_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: FUNCTION_INSTANCE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: FUNCTION_INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: FUNCTION
          value: sherpa-injector
        - name: KINGDOM
          value: prd
        - name: ESTATE
          value: prd-samtest
        - name: SUPERPOD
          value: '-'
        - name: SETTINGS_SUPERPOD
          value: '-'
        - name: SETTINGS_PATH
          value: mesh.-.prd.-.sherpa-injector
        - name: SFDC_SETTINGS_PATH
          value: mesh.-.prd.-.sherpa-injector
        - name: SFDC_METRICS_SERVICE_HOST
          value: ajnafunneldirect.localhost.mesh.force.com
        - name: SFDC_METRICS_SERVICE_PORT
          value: "7013"
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicelibs/sherpa-injector:9637c42ce66eb71611328c9ea47cb5301c38673c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ./is-alive.sh
            - "17442"
            - /client-certs/client/certificates/client.pem
            - /client-certs/client/keys/client-key.pem
          initialDelaySeconds: 2
          periodSeconds: 3
        name: injector
        ports:
        - containerPort: 17442
        readinessProbe:
          exec:
            command:
            - ./is-ready.sh
            - "17442"
            - /client-certs/client/certificates/client.pem
            - /client-certs/client/keys/client-key.pem
          initialDelaySeconds: 4
          periodSeconds: 3
        resources: {}
        volumeMounts:
        - mountPath: /server-certs
          name: cert1
        - mountPath: /client-certs
          name: cert2
      - args:
        - /sam/madkub-client
        - --madkub-endpoint=https://10.254.208.254:32007
        - --maddog-endpoint=https://all.pkicontroller.pki.blank.prd.prod.non-estates.sfdcsd.net:8443
        - --maddog-server-ca=/maddog-certs/ca/security-ca.pem
        - --madkub-server-ca=/maddog-certs/ca/cacerts.pem
        - --cert-folders=cert1:/cert1/
        - --cert-folders=cert2:/cert2/
        - --token-folder=/tokens/
        - --ca-folder=/maddog-certs/ca
        - --refresher
        - --run-init-for-refresher-mode
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4
        imagePullPolicy: IfNotPresent
        name: madkub-refresher
        volumeMounts:
        - mountPath: /cert1
          name: cert1
        - mountPath: /cert2
          name: cert2
        - mountPath: /maddog-certs/
          name: maddog-certs
        - mountPath: /tokens
          name: tokens
      - args:
        - --log-level=debug
        env:
        - name: SFDC_ENVIRONMENT
          value: mesh
        - name: SETTINGS_SERVICENAME
          value: sherpa-injector
        - name: FUNCTION_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: FUNCTION_INSTANCE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: FUNCTION_INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: FUNCTION
          value: sherpa-injector
        - name: KINGDOM
          value: prd
        - name: ESTATE
          value: prd-samtest
        - name: SUPERPOD
          value: '-'
        - name: SETTINGS_SUPERPOD
          value: '-'
        - name: SETTINGS_PATH
          value: mesh.-.prd.-.sherpa-injector
        - name: SFDC_SETTINGS_PATH
          value: mesh.-.prd.-.sherpa-injector
        - name: SFDC_METRICS_SERVICE_HOST
          value: ajna0-funnel1-0-prd.data.sfdc.net
        - name: SFDC_METRICS_SERVICE_PORT
          value: "80"
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/sfci/servicelibs/sherpa-envoy:6c67c98234e9f47f2ff9bb9c5c90acc6ac390be7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ./bin/is-alive
          initialDelaySeconds: 5
          periodSeconds: 5
        name: sherpa
        ports:
        - containerPort: 15373
        readinessProbe:
          exec:
            command:
            - ./bin/is-ready
          initialDelaySeconds: 4
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /server-certs
          name: cert1
        - mountPath: /client-certs
          name: cert2
      initContainers:
      - args:
        - /sam/madkub-client
        - --madkub-endpoint=https://10.254.208.254:32007
        - --maddog-endpoint=https://all.pkicontroller.pki.blank.prd.prod.non-estates.sfdcsd.net:8443
        - --maddog-server-ca=/maddog-certs/ca/security-ca.pem
        - --madkub-server-ca=/maddog-certs/ca/cacerts.pem
        - --cert-folders=cert1:/cert1/
        - --cert-folders=cert2:/cert2/
        - --token-folder=/tokens/
        - --ca-folder=/maddog-certs/ca
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4
        imagePullPolicy: IfNotPresent
        name: madkub-init
        volumeMounts:
        - mountPath: /cert1
          name: cert1
        - mountPath: /cert2
          name: cert2
        - mountPath: /maddog-certs/
          name: maddog-certs
        - mountPath: /tokens
          name: tokens
      - command:
        - bash
        - -c
        - |
          set -ex
          chmod 775 -R /cert1 && chown -R 7447:7447 /cert1
          chmod 775 -R /cert2 && chown -R 7447:7447 /cert2
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-c07d4afb-673
        imagePullPolicy: IfNotPresent
        name: permissionsetterinitcontainer
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /cert1
          name: cert1
        - mountPath: /cert2
          name: cert2
      nodeSelector:
        master: "true"
      volumes:
      - hostPath:
          path: /etc/pki_service
        name: maddog-certs
      - hostPath:
          path: /etc/kubernetes
        name: kubeconfig
      - emptyDir:
          medium: Memory
        name: cert1
      - emptyDir:
          medium: Memory
        name: cert2
      - emptyDir:
          medium: Memory
        name: tokens
