apiVersion: v1
data:
  tcpdumpcommand.json: |-
    {
      "tcpdumpcommands": [
        {
          "command": "-i eth0",
          "duration": "1m",
          "packetcapture": true
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: slb
  name: slb-tcpdump-ipvs
  namespace: sam-system
