apiVersion: v1
data:
  watchdog.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "deployer-funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "deployer-imageName": "ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-0001548-81d3b9bd",
      "deployer-rcImtEndpoint": "https://reportcollector-prd.data.sfdc.net:18443/v1/bark",
      "deployer-recipient": "",
      "deployer-sender": "",
      "deployer-smtpServer": "rd1-mta1-4-sfm.ops.sfdc.net:25",
      "deploymentNamespacePrefixWhitelist": "sam-system",
      "email-subject-prefix": "SAMWD",
      "enableMaddogCertChecks": true,
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "imageName": "ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-0001548-81d3b9bd",
      "k8sproxyEndpoint": "http://localhost:40000",
      "kafkaProducerEndpoint": "ajna0-broker1-0-prd.data.sfdc.net:9093",
      "kafkaTopic": "sfdc.prod.sam__prd.ajna_local__opevents",
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "kubeResourceNamespacePrefixBlacklist": "sam-watchdog",
      "kubeResourceNamespacePrefixWhitelist": "sam-system,csc-sam",
      "laddr": "0.0.0.0:8083",
      "maddogServerCAPath": "/etc/pki_service/ca/security-ca.pem",
      "maxUptimeSampleSize": 5,
      "monitoredProcesses": {
        "dockerd.*docker-bootstrap": "age.dockerbootstrap",
        "dockerd.*docker.sock": "age.dockermain",
        "hyperkube.*apiserver": "age.kubeapiserver",
        "hyperkube.*controller-manager": "age.kubecontrollermanager",
        "hyperkube.*kubelet": "age.kubelet",
        "hyperkube.*proxy": "age.kubeproxy",
        "hyperkube.*scheduler": "age.kubescheduler"
      },
      "publishAlertsToKafka": true,
      "rcImtEndpoint": "https://reportcollector-prd.data.sfdc.net:18443/v1/bark",
      "recipient": "",
      "sdpEndpoint": "http://localhost:39999",
      "sender": "",
      "smtpServer": "rd1-mta1-4-sfm.ops.sfdc.net:25",
      "snooze": [
        {
          "checker": "nodeChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "podChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "deploymentChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "estatesvcChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "prChecker",
          "estates": [
            "prd-sam"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "hairpinChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "bridgeChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "nodeChecker",
          "estates": [
            "phx-sam"
          ],
          "until": "2017/11/30"
        },
        {
          "checker": "hairpinChecker",
          "estates": [
            "prd-sam_cloudatlas",
            "prd-sam_cloudatlas_dir"
          ],
          "until": "2017/11/21"
        }
      ],
      "tlsEnabled": true
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: watchdog
  namespace: sam-system
