apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "flowsnake_master_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samkubeapi",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakemastertest1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_master_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samkubeapi",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakemastertest1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_master_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samkubeapi",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakemastertest1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_master_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samkubeapi",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakemastertest2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_master_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samkubeapi",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakemastertest2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest1-4-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest1-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest2-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest2-4-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        },
        {
          "bomrolename": "flowsnake_worker_test",
          "controlestate": "prd-data-flowsnake_test",
          "devicerole": "samcompute",
          "estate": "prd-data-flowsnake_test",
          "hostname": "fs1shared0-flowsnakeworkertest2-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sfdchosts
  namespace: flowsnake
