apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: nginx-ingress-lb
    name: nginx-ingress-lb
  name: nginx-ingress-controller
  namespace: flowsnake
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      containers:
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --sync-period=5s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: /etc/kubernetes/kubeconfig
        image: dva-registry.internal.salesforce.com/dva/flowsnake-ingress-controller-nginx:468
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        name: nginx-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        volumeMounts:
        - mountPath: /etc/ssl/certs/ssl-cert-snakeoil.pem
          name: server-certificate
          readOnly: true
        - mountPath: /etc/ssl/private/ssl-cert-snakeoil.key
          name: server-key
          readOnly: true
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/pki_service/ca
          name: certificate-authority
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/certificates
          name: client-certificate
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/keys
          name: client-key
          readOnly: true
        - mountPath: /data/certs
          name: data-cert
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - hostPath:
          path: /etc/pki_service/platform/platform-server/certificates/platform-server.pem
        name: server-certificate
      - hostPath:
          path: /etc/pki_service/platform/platform-server/keys/platform-server-key.pem
        name: server-key
      - hostPath:
          path: /etc/kubernetes/kubeconfig
        name: kubeconfig
      - hostPath:
          path: /etc/pki_service/ca
        name: certificate-authority
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/certificates
        name: client-certificate
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/keys
        name: client-key
      - hostPath:
          path: /data/certs
        name: data-cert
