apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: nginx-ingress-lb
    name: nginx-ingress-lb
  name: nginx-ingress-controller
  namespace: flowsnake
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      containers:
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --sync-period=30s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: /etc/kubernetes/kubeconfig
        image: dva-registry.internal.salesforce.com/dva/flowsnake-ingress-controller-nginx:564
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        name: nginx-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: flowsnake-tls-secret
          readOnly: true
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/pki_service/ca
          name: k8s-certificate-authority
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/certificates
          name: k8s-client-certificate
          readOnly: true
        - mountPath: /etc/pki_service/kubernetes/k8s-client/keys
          name: k8s-client-key
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: flowsnake-tls-secret
        secret:
          secretName: flowsnake-tls
      - hostPath:
          path: /etc/kubernetes/kubeconfig
        name: kubeconfig
      - hostPath:
          path: /etc/pki_service/ca
        name: k8s-certificate-authority
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/certificates
        name: k8s-client-certificate
      - hostPath:
          path: /etc/pki_service/kubernetes/k8s-client/keys
        name: k8s-client-key
