apiVersion: v1
data:
  proxyconfiguration.json: |-
    {
      "proxyconfigs": [
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-nginx-config-b"
        },
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-hsm-nginx"
        }
      ]
    }
  proxyvipmapping.json: |-
    {
      "proxyvipmappings": [
        {
          "proxyname": "slb-hsm-nginx",
          "vips": [
            "org-cce2e-cs8-slb-ord.slb.sfdc.net",
            "slb-canary-hsm.sam-system.ord-sam.ord.slb.sfdc.net"
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-proxy-configuration
  namespace: sam-system
