apiVersion: v1
data:
  proxyconfiguration.json: |-
    {
      "proxyconfigs": [
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-nginx-config-b"
        },
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-hsm-nginx"
        },
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-envoy"
        },
        {
          "healthpath": "/liveness-probe",
          "healthport": 8080,
          "name": "slb-envoy-config-b"
        }
      ]
    }
  proxyvipmapping.json: |-
    {
      "proxyvipmappings": [
        {
          "proxyname": "slb-hsm-nginx",
          "vips": [
            "slb-canary-hsm.sam-system.prd-sdc.prd.slb.sfdc.net"
          ]
        },
        {
          "proxyname": "slb-envoy",
          "vips": [
            "service-mesh-ingress.sam-system.prd-sdc.prd.slb.sfdc.net"
          ]
        },
        {
          "proxyname": "slb-envoy-config-b",
          "vips": [
            "slb-canary-envoy-svc.sam-system.prd-sdc.prd.slb.sfdc.net"
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-proxy-configuration
  namespace: sam-system
