apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-10-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-11-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "c41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-6-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute1-7-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k10-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute2-10-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "c40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute2-11-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samcompute",
          "controlestate": "prd-sdc",
          "devicerole": "samcompute",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamcompute2-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k10-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samkubeapi",
          "controlestate": "prd-sdc",
          "devicerole": "samkubeapi",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamkubeapi1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samkubeapi",
          "controlestate": "prd-sdc",
          "devicerole": "samkubeapi",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamkubeapi1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sdc_samkubeapi",
          "controlestate": "prd-sdc",
          "devicerole": "samkubeapi",
          "estate": "prd-sdc",
          "hostname": "shared0-sdcsamkubeapi3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "c40-45",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
