apiVersion: v1
data:
  bundle-controller-config.json: |-
    {
      "K4ASecretEnabled": true,
      "checkImageExistsFlag": true,
      "funnelEndpoint": "ajna0-funnel1-0-ia4.data.sfdc.net:80",
      "qps": 100,
      "resyncinterval": "60m",
      "statefulAppEnabled": true,
      "threadcount": 15,
      "whiteListNamespaceRegexp": [
        "^[^.]+"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: bundle-controller
  namespace: sam-system
