apiVersion: v1
data:
  snapshoter-mtls.json: |-
    {
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "client-cert-file": "/cert1/client/certificates/client.pem",
      "client-key-file": "/cert1/client/keys/client-key.pem",
      "enable-kafka-client-auth": true,
      "funnelEndpoint": "ajna0-funnel1-0-ia4.data.sfdc.net:80",
      "ignored-resources": [],
      "include-crds": true,
      "kafka-endpoint": "ajna0-broker1-0-ia4.data.sfdc.net:9093",
      "kafka-payload-kb": 300,
      "kafka-push-interval": "10s",
      "kafka-topic": "sfdc.prod.sam__ia4.ajna_local__resourcestatus",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "kube-poll-interval": "30m",
      "liveness-probe-port": 9095,
      "send-events": true,
      "sinks": "kafka",
      "sources": "informer"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: snapshoter-mtls
  namespace: sam-system
