apiVersion: v1
data:
  manifestwatcher.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/data/certs/hostcert.crt",
      "disableCertsCheck": true,
      "keyFile": "/data/certs/hostcert.key",
      "tlsEnabled": true,
      "tnrpArchiveEndpoint": "https://ops0-piperepo1-1-chx.ops.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: manifest-watcher
  namespace: sam-system
