apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sam_compute",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam",
          "hostname": "shared0-samcompute1-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-4",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam",
          "hostname": "shared0-samcompute1-2-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-3",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam",
          "hostname": "shared0-samcompute2-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-2",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "chx-sam",
          "devicerole": "samkubeapi",
          "estate": "chx-sam",
          "hostname": "shared0-samkubeapi1-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-1",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "chx-sam",
          "devicerole": "samkubeapi",
          "estate": "chx-sam",
          "hostname": "shared0-samkubeapi1-2-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-39",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "chx-sam",
          "devicerole": "samkubeapi",
          "estate": "chx-sam",
          "hostname": "shared0-samkubeapi2-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-1",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "chx-sam",
          "devicerole": "samkubeapi",
          "estate": "chx-sam",
          "hostname": "shared0-samkubeapi2-2-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-40",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "chx-sam",
          "devicerole": "samkubeapi",
          "estate": "chx-sam",
          "hostname": "shared0-samkubeapi3-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-2",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_gater",
          "hostname": "shared0-samminiongater1-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-5",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_gater",
          "hostname": "shared0-samminiongater1-2-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-6",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_gater",
          "hostname": "shared0-samminiongater1-3-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-7",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_gater",
          "hostname": "shared0-samminiongater2-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-3",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_gater",
          "hostname": "shared0-samminiongater2-2-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-4",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_warden",
          "hostname": "shared0-samminionwarden1-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-38",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_warden",
          "hostname": "shared0-samminionwarden2-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F07-39",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "chx-sam",
          "devicerole": "samcompute",
          "estate": "chx-sam_warden",
          "hostname": "shared0-samminionwarden3-1-chx.ops.sfdc.net",
          "kingdom": "chx",
          "pod": "none",
          "rack": "F08-38",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
