apiVersion: v1
data:
  snapshoter.json: |-
    {
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "ignored-resources": [],
      "kafka-endpoint": "ajna0-broker1-0-chx.data.sfdc.net:9093",
      "kafka-payload-kb": 300,
      "kafka-push-interval": "10s",
      "kafka-topic": "sfdc.prod.sam__chx.ajna_local__resourcestatus",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "kube-poll-interval": "30m",
      "liveness-probe-port": 9095,
      "send-events": true,
      "sinks": "kafka",
      "sources": "informer"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: snapshoter
  namespace: sam-system
