apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sam_compute",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam",
          "hostname": "shared0-samcompute1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam",
          "hostname": "shared0-samcompute1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam",
          "hostname": "shared0-samcompute2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi2-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi3-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "lo2-sam",
          "devicerole": "samkubeapi",
          "estate": "lo2-sam",
          "hostname": "shared0-samkubeapi3-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_datapool",
          "hostname": "shared0-samminiondatapool1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_datapool",
          "hostname": "shared0-samminiondatapool1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b44-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_datapool",
          "hostname": "shared0-samminiondatapool2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gater",
          "hostname": "shared0-samminiongater1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a05-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gater",
          "hostname": "shared0-samminiongater1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a05-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gater",
          "hostname": "shared0-samminiongater1-3-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a05-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gater",
          "hostname": "shared0-samminiongater2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gater",
          "hostname": "shared0-samminiongater2-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gatewayconfig",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gatewayconfig",
          "hostname": "shared0-samminiongwc1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gatewayconfig",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gatewayconfig",
          "hostname": "shared0-samminiongwc1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gatewayconfig",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gatewayconfig",
          "hostname": "shared0-samminiongwc2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b04-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gatewayconfig",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_gatewayconfig",
          "hostname": "shared0-samminiongwc2-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "b44-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion3-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a06-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-10-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a44-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-3-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-4-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-5-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-6-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-7-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-8-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "e03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion1-9-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a44-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-1-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-10-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-2-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-3-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-4-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-5-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-6-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-7-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "a03-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-8-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f15-dh01",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "lo2-sam",
          "devicerole": "samcompute",
          "estate": "lo2-slb",
          "hostname": "shared0-slbminion2-9-lo2.ops.sfdc.net",
          "kingdom": "lo2",
          "pod": "none",
          "rack": "f15-dh01",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
