apiVersion: v1
data:
  proxyconfiguration.json: |-
    {
      "proxyconfigs": [
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-nginx-config-b"
        },
        {
          "healthpath": "/",
          "healthport": 12080,
          "name": "slb-hsm-nginx"
        }
      ]
    }
  proxyvipmapping.json: |-
    {
      "proxyvipmappings": [
        {
          "proxyname": "slb-hsm-nginx",
          "vips": [
            "gs0-bofa-phx.slb.sfdc.net",
            "org-cce2e-cs3-slb-phx.slb.sfdc.net",
            "org-cce2e-cs7-slb-phx.slb.sfdc.net",
            "org-cce2e-cs9-slb-phx.slb.sfdc.net",
            "org-cce2e-cs10-slb-phx.slb.sfdc.net",
            "org-cce2e-cs11-slb-phx.slb.sfdc.net",
            "org-cce2e-cs12-slb-phx.slb.sfdc.net",
            "org-cce2e-cs13-slb-phx.slb.sfdc.net",
            "org-cce2e-cs19-slb-phx.slb.sfdc.net",
            "org-cce2e-cs20-slb-phx.slb.sfdc.net",
            "org-cce2e-cs21-slb-phx.slb.sfdc.net",
            "org-cce2e-cs23-slb-phx.slb.sfdc.net",
            "org-cce2e-cs25-slb-phx.slb.sfdc.net",
            "org-cce2e-cs26-slb-phx.slb.sfdc.net",
            "org-cce2e-cs30-slb-phx.slb.sfdc.net",
            "org-cce2e-cs50-slb-phx.slb.sfdc.net",
            "org-cce2e-cs51-slb-phx.slb.sfdc.net",
            "org-cce2e-cs52-slb-phx.slb.sfdc.net",
            "org-cce2e-cs53-slb-phx.slb.sfdc.net",
            "org-cce2e-cs54-slb-phx.slb.sfdc.net",
            "org-cce2e-cs59-slb-phx.slb.sfdc.net",
            "org-cce2e-cs60-slb-phx.slb.sfdc.net",
            "org-cce2e-cs61-slb-phx.slb.sfdc.net",
            "org-cce2e-cs62-slb-phx.slb.sfdc.net",
            "org-cce2e-cs63-slb-phx.slb.sfdc.net",
            "org-cce2e-cs68-slb-phx.slb.sfdc.net",
            "org-cce2e-cs69-slb-phx.slb.sfdc.net",
            "org-cce2e-cs70-slb-phx.slb.sfdc.net",
            "org-cce2e-cs71-slb-phx.slb.sfdc.net",
            "org-cce2e-cs90-slb-phx.slb.sfdc.net",
            "org-cce2e-cs91-slb-phx.slb.sfdc.net",
            "org-cce2e-cs999-slb-phx.slb.sfdc.net",
            "org-orgcerttest-gs0-slb-phx.slb.sfdc.net",
            "org-cce2e-na47-slb-phx.slb.sfdc.net",
            "slb-canary-hsm.sam-system.phx-sam.phx.slb.sfdc.net"
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: slb-proxy-configuration
  namespace: sam-system
