apiVersion: v1
data:
  tempmanifestwatcher.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "crdDeletionEnabled": true,
      "crdEnabled": true,
      "deletionPercentageThreshold": 20,
      "disableCertsCheck": true,
      "etcdAppFolder": "",
      "k4aEnabled": true,
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "livenessProbePort": "21553",
      "lockName": "",
      "manifestV1Enabled": false,
      "skipOldZips": true,
      "tlsEnabled": true,
      "tnrpArchiveEndpoint": "https://ops0-piperepo1-0-phx.data.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: crd-watcher
  namespace: sam-system
