apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: v2.4.0-v1beta1
  name: spark-operator
  namespace: flowsnake
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-operator
      app.kubernetes.io/version: v2.4.0-v1beta1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-operator
        app.kubernetes.io/version: v2.4.0-v1beta1
    spec:
      containers:
      - args:
        - -logtostderr
        - -v=2
        - -enable-metrics=true
        - -metrics-port=10254
        - -metrics-endpoint=/metrics
        command:
        - /usr/bin/spark-operator
        image: ops0-artifactrepo1-0-frf.data.sfdc.net/dva/kubernetes-spark-operator-2.4.0-sfdc-0.0.1:11
        imagePullPolicy: Always
        name: spark-operator
        ports:
        - containerPort: 10254
          name: metrics
          protocol: TCP
      serviceAccountName: spark-operator
