apiVersion: v1
data:
  slbportallinks.json: |-
    {
      "links": [
        {
          "href": "https://slb-portal-frf.slb.sfdc.net",
          "name": "frf"
        },
        {
          "href": "https://slb-portal-phx.slb.sfdc.net",
          "name": "phx"
        },
        {
          "href": "https://slb-portal-iad.slb.sfdc.net",
          "name": "iad"
        },
        {
          "href": "https://slb-portal-ord.slb.sfdc.net",
          "name": "ord"
        },
        {
          "href": "https://slb-portal-dfw.slb.sfdc.net",
          "name": "dfw"
        },
        {
          "href": "https://slb-portal-hnd.slb.sfdc.net",
          "name": "hnd"
        },
        {
          "href": "https://slb-portal-xrd.slb.sfdc.net",
          "name": "xrd"
        },
        {
          "href": "https://slb-portal-cdg.slb.sfdc.net",
          "name": "cdg"
        },
        {
          "href": "https://slb-portal-fra.slb.sfdc.net",
          "name": "fra"
        },
        {
          "href": "https://slb-portal-ia2.slb.sfdc.net",
          "name": "ia2"
        },
        {
          "href": "https://slb-portal-ph2.slb.sfdc.net",
          "name": "ph2"
        },
        {
          "href": "https://slb-portal-par.slb.sfdc.net",
          "name": "par"
        },
        {
          "href": "https://slb-portal-ukb.slb.sfdc.net",
          "name": "ukb"
        },
        {
          "href": "https://slb-portal-lo2.slb.sfdc.net",
          "name": "lo2"
        },
        {
          "href": "https://slb-portal-lo3.slb.sfdc.net",
          "name": "lo3"
        },
        {
          "href": "https://slb-portal-ia4.slb.sfdc.net",
          "name": "ia4"
        },
        {
          "href": "https://slb-portal-ia5.slb.sfdc.net",
          "name": "ia5"
        },
        {
          "href": "http://slb-portal-service.sam-system.prd-sam.prd.slb.sfdc.net:9112/",
          "name": "prd-sam"
        },
        {
          "href": "http://slb-portal-service.sam-system.prd-samtwo.prd.slb.sfdc.net:9112/",
          "name": "prd-samtwo"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: slb
  name: slb-portal-links
  namespace: sam-system
