apiVersion: v1
data:
  host-repair-aggregator.json: |-
    {
      "crdNamespace": "sam-system",
      "crdPollFrequency": "5m",
      "crdPushFrequency": "5m",
      "dbHostname": "mysql-inmem-0.mysql-inmem-service.sam-system",
      "dbPasswordFile": "/var/mysqlPwd/host-repair-agg",
      "dbUsername": "host-repair-agg",
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "k8sCeListFromDB": [
        "cdg-sam",
        "cdu-sam",
        "dfw-sam",
        "fra-sam",
        "frf-sam",
        "hio-sam",
        "hnd-sam",
        "ia2-sam",
        "iad-sam",
        "lo2-sam",
        "lo3-sam",
        "ord-sam",
        "par-sam",
        "ph2-sam",
        "phx-sam",
        "prd-sam",
        "prd-samtwo",
        "prd-samdev",
        "syd-sam",
        "ttd-sam",
        "ukb-sam",
        "xrd-sam",
        "yhu-sam",
        "yul-sam"
      ],
      "k8sFromDB": true,
      "k8sResourceDbName": "sam_kube_resource",
      "k8sResourceTableName": "k8s_resource",
      "nodeOfflineAfterTime": "60m",
      "signals": [
        "filesystemChecker",
        "kubeletChecker",
        "cliChecker.DockerDaemon",
        "procUpTime"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: host-repair-aggregator
  namespace: sam-system
