apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  annotations:
    manifestctl.sam.data.sfdc.net/swagger: disable
  name: istio-mtls-enable
  namespace: service-mesh
spec:
  peers:
  - mtls: {}
