apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    manifestctl.sam.data.sfdc.net/swagger: disable
  name: route-update-service
  namespace: service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-update-service
      settings_path: test.-.prd.-.route-update-service
      superpod: NONE
  template:
    metadata:
      annotations:
        madkub.sam.sfdc.net/allcerts: |-
          {
           "certreqs": [
            {
             "cert-type": "server",
             "kingdom": "prd",
             "name": "server-cert",
             "role": "route-update-service.service-mesh",
             "san": [
              "route-update-service",
              "route-update-service.service-mesh",
              "route-update-service.service-mesh.svc",
              "route-update-service.service-mesh.svc.prd-sam.prd.sam.sfdc.net"
             ]
            }
           ]
          }
        sidecar.istio.io/inject: "false"
      labels:
        app: route-update-service
        settings_path: test.-.prd.-.route-update-service
        superpod: NONE
    spec:
      containers:
      - args: []
        env:
        - name: ESTATE
          value: prd-sam_gater
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-sfci-dev/sfci/servicemesh/servicemesh/route-update-service:b817daada3298bf9b1c337fb383f67949615b342
        imagePullPolicy: IfNotPresent
        name: route-update-service
        ports:
        - containerPort: 7020
          name: grpc-svc
        readinessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/pki_service
          name: maddog-certs
        - mountPath: /server-cert
          name: server-cert
        - mountPath: /client-certs
          name: tls-client-cert
        - mountPath: /server-certs
          name: tls-server-cert
      - args:
        - /sam/madkub-client
        - --madkub-endpoint=https://10.254.208.254:32007
        - --maddog-endpoint=https://all.pkicontroller.pki.blank.prd.prod.non-estates.sfdcsd.net:8443
        - --maddog-server-ca=/maddog-certs/ca/security-ca.pem
        - --madkub-server-ca=/maddog-certs/ca/cacerts.pem
        - --cert-folders=server-cert:/server-cert/
        - --token-folder=/tokens/
        - --ca-folder=/maddog-certs/ca
        - --refresher
        - --run-init-for-refresher-mode
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4
        imagePullPolicy: IfNotPresent
        name: madkub-refresher
        resources: {}
        volumeMounts:
        - mountPath: /server-cert
          name: server-cert
        - mountPath: /maddog-certs/
          name: maddog-certs
        - mountPath: /tokens
          name: tokens
      nodeSelector:
        pool: prd-sam_gater
      serviceAccountName: route-update-service-service-account
      volumes:
      - hostPath:
          path: /etc/pki_service
        name: maddog-certs
      - maddogCert:
          type: client
        name: tls-client-cert
      - maddogCert:
          type: server
        name: tls-server-cert
