apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: slb-nginx-config-a
  name: slb-nginx-config-a
  namespace: sam-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: slb-nginx-config-a
      namespace: sam-system
    spec:
      containers:
      - command:
        - /sdn/slb-nginx-config
        - --configDir=/host/data/slb/config
        - --target=/host/data/slb/nginx/config
        - --netInterfaceName=eth0
        - --metricsEndpoint=ajna0-funnel1-0-prd.data.sfdc.net:80
        - --log_dir=/host/data/slb/logs
        - --maxDeleteServiceCount=3
        - --hostsConfigFile=/sfdchosts/hosts.json
        - --httpsEnabled=slb-canary-proxy-http.sam-system.prd-sam.prd.slb.sfdc.net
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sdn/hypersdn:v-0000652-a10bc60a
        name: slb-nginx-config-a
        ports:
        - containerPort: 32146
          name: slb-nginx-port
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/data/slb/nginx/config
          name: var-target-config-volume
        - mountPath: /host/data/slb/config
          name: var-config-volume
        - mountPath: /host/data/slb/logs
          name: var-logs-volume
        - mountPath: /sfdchosts
          name: sfdchosts
      - command:
        - /runner.sh
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sdn/slb-nginx:v-0000019-722fb3a3
        livenessProbe:
          httpGet:
            path: /
            port: 12080
          initialDelaySeconds: 15
          periodSeconds: 10
        name: slb-nginx-proxy-a
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: var-target-config-volume
        - mountPath: /host/data/slb/logs
          name: var-logs-volume
      - command:
        - /sdn/slb-file-watcher
        - --filePath=/host/data/slb/logs/slb-nginx-proxy.emerg.log
        - --metricName=nginx-emergency
        - --lastModReportTime=120s
        - --scanPeriod=10s
        - --skipZeroLengthFiles=true
        - --metricsEndpoint=ajna0-funnel1-0-prd.data.sfdc.net:80
        - --log_dir=/host/data/slb/logs
        - --hostsConfigFile=/sfdchosts/hosts.json
        image: ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sdn/hypersdn:v-0000652-a10bc60a
        name: slb-file-watcher
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: var-target-config-volume
        - mountPath: /host/data/slb/logs
          name: var-logs-volume
        - mountPath: /sfdchosts
          name: sfdchosts
      hostNetwork: true
      nodeSelector:
        slb-service: slb-nginx-a
      volumes:
      - hostPath:
          path: /data/slb/nginx/config
        name: var-target-config-volume
      - hostPath:
          path: /data/slb/config
        name: var-config-volume
      - hostPath:
          path: /data/slb/logs
        name: var-logs-volume
      - configMap:
          name: sfdchosts
        name: sfdchosts
