apiVersion: v1
data:
  snapshoter.json: |-
    {
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "recipient": "sam@salesforce.com",
      "sink": "logs"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: snapshoter
  namespace: sam-system
