apiVersion: v1
data:
  snapshot-consumer-prod-mtls.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "clientCertFile": "/cert1/client/certificates/client.pem",
      "clientKeyFile": "/cert1/client/keys/client-key.pem",
      "consumeTableName": "consume",
      "dbHostname": "mysql-inmem-service.sam-system.prd-sam.prd.slb.sfdc.net",
      "dbPasswordFile": "/var/mysqlPwd/ssc-prod",
      "dbUsername": "ssc-prod",
      "enableKafkaClientAuth": true,
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "k8sResourceDbName": "sam_kube_resource",
      "k8sResourceTableName": "k8s_resource",
      "kafkaClientId": "snapshot-consumer-prod",
      "kafkaConsumerEndpoint": "ajna0-brokeragg1-0-prd.data.sfdc.net:9093",
      "kafkaTopics": "sfdc.prod.sam__cdg.ajna_local__resourcestatus,sfdc.prod.sam__cdu.ajna_local__resourcestatus,sfdc.prod.sam__chx.ajna_local__resourcestatus,sfdc.prod.sam__dfw.ajna_local__resourcestatus,sfdc.prod.sam__fra.ajna_local__resourcestatus,sfdc.prod.sam__frf.ajna_local__resourcestatus,sfdc.prod.sam__hio.ajna_local__resourcestatus,sfdc.prod.sam__hnd.ajna_local__resourcestatus,sfdc.prod.sam__ia2.ajna_local__resourcestatus,sfdc.prod.sam__ia4.ajna_local__resourcestatus,sfdc.prod.sam__ia5.ajna_local__resourcestatus,sfdc.prod.sam__iad.ajna_local__resourcestatus,sfdc.prod.sam__lo2.ajna_local__resourcestatus,sfdc.prod.sam__lo3.ajna_local__resourcestatus,sfdc.prod.sam__ord.ajna_local__resourcestatus,sfdc.prod.sam__par.ajna_local__resourcestatus,sfdc.prod.sam__ph2.ajna_local__resourcestatus,sfdc.prod.sam__phx.ajna_local__resourcestatus,sfdc.prod.sam__prd.ajna_local__resourcestatus,sfdc.prod.sam__syd.ajna_local__resourcestatus,sfdc.prod.sam__ttd.ajna_local__resourcestatus,sfdc.prod.sam__ukb.ajna_local__resourcestatus,sfdc.prod.sam__wax.ajna_local__resourcestatus,sfdc.prod.sam__xrd.ajna_local__resourcestatus,sfdc.prod.sam__yhu.ajna_local__resourcestatus,sfdc.prod.sam__yul.ajna_local__resourcestatus",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: snapshot-consumer-prod-mtls
  namespace: sam-system
