apiVersion: v1
data:
  watchdog.json: |-
    {
      "ManifestTnrpEndpoint": "https://ops0-piperepo1-0-prd.data.sfdc.net/tnrp/content_repo/0/archive",
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "deployer-funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "deployer-imageName": "ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-0001667-72dcabb0",
      "deployer-rcImtEndpoint": "https://reportcollector-prd.data.sfdc.net:18443/v1/bark",
      "deployer-recipient": "sam-test-alerts@salesforce.com",
      "deployer-sender": "sam-test-alerts@salesforce.com",
      "deployer-smtpServer": "rd1-mta1-4-sfm.ops.sfdc.net:25",
      "deploymentNamespacePrefixWhitelist": "sam-system",
      "email-subject-prefix": "SAMWD",
      "enableMaddogCertChecks": true,
      "enableStatefulChecks": true,
      "enableStatefulPVChecks": true,
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "imageName": "ops0-artifactrepo2-0-prd.data.sfdc.net/docker-release-candidate/tnrp/sam/hypersam:sam-0001667-72dcabb0",
      "k8sproxyEndpoint": "http://localhost:40000",
      "kafkaProducerEndpoint": "ajna0-broker1-0-prd.data.sfdc.net:9093",
      "kafkaTopic": "sfdc.prod.sam__prd.ajna_local__opevents",
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "kubeResourceNamespacePrefixBlacklist": "sam-watchdog",
      "kubeResourceNamespacePrefixWhitelist": "sam-system,csc-sam",
      "laddr": "0.0.0.0:8063",
      "maddogCommonCerts": [
        "/etc/pki_service/kubernetes/k8s-server/certificates/k8s-server.pem",
        "/etc/pki_service/kubernetes/k8s-client/certificates/k8s-client.pem",
        "/etc/pki_service/etcd/etcd-client/certificates/etcd-client.pem",
        "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
        "/etc/pki_service/root/madkubtokenserver/certificates/madkubtokenserver.pem"
      ],
      "maddogEtcdCerts": [
        "/etc/pki_service/etcd/etcd-server/certificates/etcd-server.pem",
        "/etc/pki_service/etcd/etcd-peer/certificates/etcd-peer.pem"
      ],
      "maddogServerCAPath": "/etc/pki_service/ca/security-ca.pem",
      "maxPVCAge": 420000000000,
      "maxUptimeSampleSize": 5,
      "maxdeploymentduration": 420000000000,
      "monitoredProcesses": {
        "dockerd.*docker-bootstrap": "age.dockerbootstrap",
        "dockerd.*docker.sock": "age.dockermain",
        "hyperkube.*apiserver": "age.kubeapiserver",
        "hyperkube.*controller-manager": "age.kubecontrollermanager",
        "hyperkube.*kubelet": "age.kubelet",
        "hyperkube.*proxy": "age.kubeproxy",
        "hyperkube.*scheduler": "age.kubescheduler",
        "name=etcd": "age.etcd"
      },
      "publishAlertsToKafka": true,
      "publishAllReportsToKafka": true,
      "rcImtEndpoint": "https://reportcollector-prd.data.sfdc.net:18443/v1/bark",
      "recipient": "sam-test-alerts@salesforce.com",
      "sdpEndpoint": "http://localhost:39999",
      "sender": "sam-test-alerts@salesforce.com",
      "smtpServer": "rd1-mta1-4-sfm.ops.sfdc.net:25",
      "snooze": [
        {
          "checker": "nodeChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "podChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "deploymentChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "estatesvcChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "prChecker",
          "estates": [
            "prd-sam"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "hairpinChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "bridgeChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "nodeChecker",
          "estates": [
            "phx-sam"
          ],
          "until": "2017/11/30"
        },
        {
          "checker": "syntheticChecker",
          "estates": [
            "chx-sam",
            "wax-sam"
          ],
          "until": "2017/12/31"
        },
        {
          "checker": "hairpinChecker",
          "estates": [
            "prd-sam_cloudatlas",
            "prd-sam_cloudatlas_dir"
          ],
          "until": "2017/11/21"
        }
      ],
      "storageClassName": "synthetic-hdd-pool",
      "syntheticPVRetrytimeout": 420000000000,
      "syntheticretrytimeout": 420000000000,
      "tlsEnabled": true
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: watchdog
  namespace: sam-watchdog
