apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    manifestctl.sam.data.sfdc.net/swagger: disable
  labels:
    app: istio-ingressgateway
    release: istio
  name: istio-ingressgateway-service-account
  namespace: core-on-sam-sp2
