apiVersion: v1
data:
  crd-12.yaml: |-
    kind: CustomResourceDefinition
    apiVersion: apiextensions.k8s.io/v1beta1
    metadata:
      name: authorizationpolicies.rbac.istio.io
      labels:
        app: istio-pilot
        istio: rbac
        heritage: Tiller
        release: istio
    spec:
      group: rbac.istio.io
      names:
        kind: AuthorizationPolicy
        plural: authorizationpolicies
        singular: authorizationpolicy
        categories:
          - istio-io
          - rbac-istio-io
      scope: Namespaced
      version: v1alpha1
    ---
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: istio-crd-12
  namespace: mesh-control-plane
