apiVersion: v1
data:
  manifestwatcher.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "disableCertsCheck": true,
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "tlsEnabled": true,
      "tnrpArchiveEndpoint": "https://ops0-piperepo1-0-par.data.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: manifest-watcher
  namespace: sam-system
