apiVersion: v1
data:
  watchdog.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/data/certs/hostcert.crt",
      "deployer-funnelEndpoint": "mandm-funnel-par1.data.sfdc.net:8080",
      "deployer-imageName": "ops0-artifactrepo1-0-par.data.sfdc.net/tnrp/sam/hypersam:sam-0001489-165e1293",
      "deployer-rcImtEndpoint": "https://ops0-health1-1-par.ops.sfdc.net:18443/v1/bark",
      "deployer-recipient": "sam-alerts@salesforce.com",
      "deployer-sender": "sam-alerts@salesforce.com",
      "deployer-smtpServer": "ops0-mta2-1-par.ops.sfdc.net:25",
      "email-subject-prefix": "SAMWD",
      "enableMaddogCertChecks": true,
      "funnelEndpoint": "mandm-funnel-par1.data.sfdc.net:8080",
      "imageName": "ops0-artifactrepo1-0-par.data.sfdc.net/tnrp/sam/hypersam:sam-0001489-165e1293",
      "k8sproxyEndpoint": "http://localhost:40000",
      "keyFile": "/data/certs/hostcert.key",
      "laddr": "0.0.0.0:8083",
      "maddogServerCAPath": "/etc/pki_service/ca/security-ca.pem",
      "maxUptimeSampleSize": 5,
      "podNamespacePrefixBlacklist": "sam-watchdog",
      "rcImtEndpoint": "https://ops0-health1-1-par.ops.sfdc.net:18443/v1/bark",
      "recipient": "sam-alerts@salesforce.com",
      "sdpEndpoint": "http://localhost:39999",
      "sender": "sam-alerts@salesforce.com",
      "smtpServer": "ops0-mta2-1-par.ops.sfdc.net:25",
      "snooze": [
        {
          "checker": "nodeChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "podChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "deploymentChecker",
          "estates": [
            "iad-sam"
          ],
          "until": "2017/09/15"
        },
        {
          "checker": "estatesvcChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "prChecker",
          "estates": [
            "prd-sam"
          ],
          "until": "2017/10/01"
        },
        {
          "checker": "hairpinChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "bridgeChecker",
          "estates": [
            "prd-sam",
            "prd-samtest",
            "prd-samdev",
            "prd-sam_storage"
          ],
          "until": "2017/11/01"
        },
        {
          "checker": "nodeChecker",
          "estates": [
            "phx-sam"
          ],
          "until": "2017/11/30"
        }
      ],
      "tlsEnabled": true
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: watchdog
  namespace: sam-watchdog
