apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sam_compute",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam",
          "hostname": "shared0-samcompute1-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-3",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam",
          "hostname": "shared0-samcompute1-2-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-4",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_compute",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam",
          "hostname": "shared0-samcompute2-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-2",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "wax-sam",
          "devicerole": "samkubeapi",
          "estate": "wax-sam",
          "hostname": "shared0-samkubeapi1-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-1",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "wax-sam",
          "devicerole": "samkubeapi",
          "estate": "wax-sam",
          "hostname": "shared0-samkubeapi1-2-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-39",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "wax-sam",
          "devicerole": "samkubeapi",
          "estate": "wax-sam",
          "hostname": "shared0-samkubeapi2-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-1",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "wax-sam",
          "devicerole": "samkubeapi",
          "estate": "wax-sam",
          "hostname": "shared0-samkubeapi2-2-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-40",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "wax-sam",
          "devicerole": "samkubeapi",
          "estate": "wax-sam",
          "hostname": "shared0-samkubeapi3-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-2",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam_gater",
          "hostname": "shared0-samminiongater1-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-5",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam_gater",
          "hostname": "shared0-samminiongater1-2-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-6",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam_gater",
          "hostname": "shared0-samminiongater1-3-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "B01-7",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam_gater",
          "hostname": "shared0-samminiongater2-1-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-3",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "wax-sam",
          "devicerole": "samcompute",
          "estate": "wax-sam_gater",
          "hostname": "shared0-samminiongater2-2-wax.ops.sfdc.net",
          "kingdom": "wax",
          "pod": "none",
          "rack": "C01-4",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
