apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: watchdog-deployment
  name: watchdog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watchdog-deployment
  template:
    metadata:
      labels:
        apptype: monitoring
        name: watchdog-deployment
      namespace: sam-system
    spec:
      containers:
      - command:
        - /sam/watchdog
        - -role=DEPLOYMENT
        - -watchdogFrequency=10s
        - -alertThreshold=1h
        - -timeout=2s
        - -funnelEndpoint=mandm-funnel-wax.data.sfdc.net:8080
        - --config=/config/watchdog.json
        - --hostsConfigFile=/sfdchosts/hosts.json
        - -emailFrequency=24h
        env:
        - name: KUBECONFIG
          value: /kubeconfig/kubeconfig
        image: ops-artifactrepo1-0-wax.data.sfdc.net/tnrp/sam/hypersam:sam-0001710-3ec484d6
        name: watchdog-deployment
        volumeMounts:
        - mountPath: /sfdchosts
          name: sfdchosts
        - mountPath: /data/certs
          name: certs
        - mountPath: /kubeconfig
          name: kubeconfig
        - mountPath: /config
          name: config
      hostNetwork: true
      nodeSelector:
        pool: wax-sam
      volumes:
      - configMap:
          name: sfdchosts
        name: sfdchosts
      - hostPath:
          path: /data/certs
        name: certs
      - hostPath:
          path: /etc/kubernetes
        name: kubeconfig
      - configMap:
          name: watchdog
        name: config
