apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "ast-sam",
          "devicerole": "samkubeapi",
          "estate": "ast-sam",
          "hostname": "shared0-samkubeapi1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_kube_api",
          "controlestate": "ast-sam",
          "devicerole": "samkubeapi",
          "estate": "ast-sam",
          "hostname": "shared0-samkubeapi2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_datapool",
          "hostname": "shared0-samminiondatapool1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_datapool",
          "hostname": "shared0-samminiondatapool2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_datapool",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_datapool",
          "hostname": "shared0-samminiondatapool3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_dp",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_dp",
          "hostname": "shared0-samminiondp1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_dp",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_dp",
          "hostname": "shared0-samminiondp2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_dp",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_dp",
          "hostname": "shared0-samminiondp3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_gater",
          "hostname": "shared0-samminiongater1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_gater",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_gater",
          "hostname": "shared0-samminiongater2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion1-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_kingdom_caas",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_kingdom_caas",
          "hostname": "samkingdomcaas0-caasminion3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_report_collector",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_report_collector",
          "hostname": "shared0-samminionreportcollector1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_report_collector",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_report_collector",
          "hostname": "shared0-samminionreportcollector2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch1-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch1-3-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch1-4-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch1-5-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch2-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch2-3-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch2-4-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch2-5-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch3-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch3-3-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch3-4-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_search",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_search",
          "hostname": "shared0-samminionsearch3-5-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_warden",
          "hostname": "shared0-samminionwarden1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_warden",
          "hostname": "shared0-samminionwarden2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_warden",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sam_warden",
          "hostname": "shared0-samminionwarden3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sdn_control",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sdn_control",
          "hostname": "shared0-sdncontrol1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sdn_control",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-sdn_control",
          "hostname": "shared0-sdncontrol1-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_sme",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-search_model_executor",
          "hostname": "shared0-samminionsme1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_sme",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-search_model_executor",
          "hostname": "shared0-samminionsme1-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_sme",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-search_model_executor",
          "hostname": "shared0-samminionsme2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_sme",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-search_model_executor",
          "hostname": "shared0-samminionsme2-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_sme",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-search_model_executor",
          "hostname": "shared0-samminionsme3-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-slb",
          "hostname": "shared0-slbminion1-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-slb",
          "hostname": "shared0-slbminion1-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-slb",
          "hostname": "shared0-slbminion2-1-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        },
        {
          "bomrolename": "slb_minion",
          "controlestate": "ast-sam",
          "devicerole": "samcompute",
          "estate": "ast-slb",
          "hostname": "shared0-slbminion2-2-ast.ops.sfdc.net",
          "kingdom": "ast",
          "pod": "none",
          "rack": "",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
