apiVersion: v1
data:
  samapp-controller-config.json: |-
    {
      "dnsEnabledPoolNamesRegex": ".*",
      "dockerRegistry": "ops0-artifactrepo1-0-xrd.data.sfdc.net",
      "enableDNS": true,
      "enableIdentityEnvVar": false,
      "enableMaddog": true,
      "funnelEndpoint": "ajna0-funnel1-0-xrd.data.sfdc.net:80",
      "imagePullPolicy": "Always",
      "k4aInitContainerImage": "ops0-artifactrepo1-0-xrd.data.sfdc.net/tnrp/sam/hypersam:sam-0002447-69fdc914",
      "maddogMaddogEndpoint": "https://all.pkicontroller.pki.blank.xrd.prod.non-estates.sfdcsd.net:8443",
      "madkubImage": "ops0-artifactrepo1-0-xrd.data.sfdc.net/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4",
      "namespaceHostSubList": [
        ".*"
      ],
      "volPermissionInitContainerImage": "ops0-artifactrepo1-0-xrd.data.sfdc.net/tnrp/sam/hypersam:sam-1ebeb0ac-657"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: samapp-controller
  namespace: sam-system
