apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v06-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "aa34-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u04-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "b20-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_merger",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_merger",
          "hostname": "shared0-samminiontnrpmerger2-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_promoter",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_promoter",
          "hostname": "shared0-samminiontnrppromoter1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_promoter",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_promoter",
          "hostname": "shared0-samminiontnrppromoter1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v06-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_promoter",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_promoter",
          "hostname": "shared0-samminiontnrppromoter2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u04-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_signer",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_signer",
          "hostname": "shared0-samminiontnrpsigner1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v06-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_signer",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_signer",
          "hostname": "shared0-samminiontnrpsigner1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_tnrp_signer",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sam_tnrp_signer",
          "hostname": "shared0-samminiontnrpsigner2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u04-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_compute",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwocompute1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "d38-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_compute",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwocompute1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "q09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_compute",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwocompute2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "w03-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_kube_api",
          "controlestate": "prd-samtwo",
          "devicerole": "samkubeapi",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwokubeapi1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p32-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_kube_api",
          "controlestate": "prd-samtwo",
          "devicerole": "samkubeapi",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwokubeapi1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_kube_api",
          "controlestate": "prd-samtwo",
          "devicerole": "samkubeapi",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwokubeapi2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "w35-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_kube_api",
          "controlestate": "prd-samtwo",
          "devicerole": "samkubeapi",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwokubeapi2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samtwo_kube_api",
          "controlestate": "prd-samtwo",
          "devicerole": "samkubeapi",
          "estate": "prd-samtwo",
          "hostname": "shared0-samtwokubeapi3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "m40-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "d24-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p35-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "b34-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "q09-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "c41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "slbtwo_minion",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-slbtwo",
          "hostname": "shared0-slbtwominion2-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "q07-45",
          "superpod": "none"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "m31-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "e35-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "j08-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-4-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "d06-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v10-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-6-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "t07-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-7-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "f34-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion1-8-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p04-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "p31-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k08-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k08-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-4-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v09-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "t10-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-6-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u07-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-7-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "s03-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-8-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "s03-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion2-9-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v03-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "h38-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "h38-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-3-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "d38-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-4-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v07-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-5-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "w03-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-6-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "k23-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-7-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u04-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-8-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u03-45",
          "superpod": "sp2"
        },
        {
          "bomrolename": "sam_minion_caas",
          "controlestate": "prd-samtwo",
          "devicerole": "samcompute",
          "estate": "prd-sp2-sam_caas",
          "hostname": "samcaas2-caasminion3-9-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "u03-45",
          "superpod": "sp2"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
