apiVersion: v1
data:
  samapp-controller-config.json: |-
    {
      "dnsEnabledPoolNamesRegex": ".*",
      "dockerRegistry": "ops0-artifactrepo1-0-frf.data.sfdc.net",
      "enableDNS": true,
      "enableIdentityEnvVar": false,
      "enableMaddog": true,
      "enableStatefulSet": true,
      "funnelEndpoint": "mandm-funnel-frf1.data.sfdc.net:8080",
      "imagePullPolicy": "IfNotPresent",
      "k4aInitContainerImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/dva/sam/hypersam:2778-29ee2fa3a4532165211b8adae39ecf04c451a410",
      "maddogMaddogEndpoint": "https://all.pkicontroller.pki.blank.frf.prod.non-estates.sfdcsd.net:8443",
      "madkubImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4",
      "namespaceHostSubList": [
        "cloudatlas"
      ],
      "volPermissionInitContainerImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/tnrp/sam/hypersam:sam-1ebeb0ac-657"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: samapp-controller
  namespace: sam-system
