apiVersion: v1
data:
  samcontrol.json: |-
    {
      "blackListNamespaceRegexp": [
        "e2e-.*-csc-sam$",
        "^[^.]+"
      ],
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "checkImageExistsFlag": true,
      "createTPR": false,
      "debug": true,
      "deletionEnabled": true,
      "deletionPercentageThreshold": 20,
      "dnsEnabledPoolNamesRegex": ".*",
      "dockerregistry": "ops0-artifactrepo1-0-frf.data.sfdc.net",
      "enableDNS": true,
      "enableIdentityEnvVar": false,
      "enableMaddog": true,
      "httpsDisableCertsCheck": true,
      "imageCheckV2": true,
      "k4aInitContainerImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/dva/sam/hypersam:2778-29ee2fa3a4532165211b8adae39ecf04c451a410",
      "k8sapiserver": "",
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "livenessProbePort": "22545",
      "maddogMaddogEndpoint": "https://all.pkicontroller.pki.blank.frf.prod.non-estates.sfdcsd.net:8443",
      "maddogMadkubImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/tnrp/sam/madkub:1.0.0-0000082-3d5c21b4",
      "slbConfigInAnnotations": false,
      "slbConfigInLabels": false,
      "statefulAppEnabled": true,
      "tlsEnabled": true,
      "volPermissionInitContainerImage": "ops0-artifactrepo1-0-frf.data.sfdc.net/tnrp/sam/hypersam:sam-1ebeb0ac-657"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: samcontrol
  namespace: sam-system
