apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: slb-config-data
  name: slb-config-data
  namespace: sam-system
spec:
  template:
    metadata:
      labels:
        apptype: control
        daemonset: "true"
        name: slb-config-data
      namespace: sam-system
    spec:
      containers:
      - command:
        - /sdn/slb-config-data
        - --port=9117
        image: ops0-artifactrepo1-0-frf.data.sfdc.net/tnrp/sdn/hypersdn:v-0000748-d1fa158b
        name: slb-config-data
        volumeMounts:
        - mountPath: /host/data/slb
          name: var-slb-volume
      hostNetwork: true
      volumes:
      - hostPath:
          path: /data/slb
        name: var-slb-volume
