apiVersion: v1
data:
  tempsamcontroldeployer.json: |-
    {
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "delete-orphans": false,
      "disable-rollback": true,
      "disable-security-check": true,
      "dry-run": false,
      "email": true,
      "email-delay": 0,
      "etcd-directory": "/temp/secrets/",
      "funnelEndpoint": "mandm-funnel-frf1.data.sfdc.net:8080",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "max-resource-time": 300000000000,
      "poll-delay": 30000000000,
      "recipient": "cbatra@salesforce.com",
      "resource-cooldown": 15000000000,
      "resource-progression-timeout": 120000000000,
      "sender": "sam@salesforce.com",
      "smtp-server": "ops0-mta2-1-frf.ops.sfdc.net:25",
      "src-root": "temp-secrets/",
      "tnrp-endpoint": "https://ops0-piperepo1-1-frf.ops.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: temp-samcontrol-deployer
  namespace: sam-system
