apiVersion: v1
data:
  samcontroldeployer.json: |-
    {
      "app-key-ttl-duration": "12h",
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "delete-orphans": true,
      "disable-security-check": true,
      "dry-run": false,
      "email": true,
      "email-delay": 0,
      "funnelEndpoint": "ajna0-funnel1-0-ia5.data.sfdc.net:80",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "max-resource-time": "20m",
      "poll-delay": 30000000000,
      "prevent-rewind": true,
      "recipient": "sam@salesforce.com",
      "resource-cooldown": 15000000000,
      "resource-progression-timeout": 120000000000,
      "resources-to-skip": [
        "sdn-secret.yaml"
      ],
      "sender": "sam@salesforce.com",
      "smtp-server": "ops0-mta2-1-ia5.ops.sfdc.net:25",
      "tnrp-endpoint": "https://ops0-piperepo1-0-ia5.data.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: samcontrol-deployer
  namespace: sam-system
