apiVersion: v1
data:
  samapp-controller-config.json: |-
    {
      "dnsEnabledPoolNamesRegex": ".*",
      "dockerRegistry": "",
      "enableDNS": true,
      "enableIdentityEnvVar": false,
      "enableMaddog": true,
      "enableStatefulSet": true,
      "funnelEndpoint": "funnel.ajnalocal1.vip.core.test.us-central1.gcp.sfdc.net:443",
      "imagePullPolicy": "Always",
      "k4aInitContainerImage": "ops0-artifactrepo2-0-xrd.slb.sfdc.net/docker-gcp/dva/sam/hypersam:2601-1bbc5de4786678763a4e8a71681ee42ada887c76",
      "maddogMaddogEndpoint": "https://10.168.195.227:8443",
      "madkubImage": "ops0-artifactrepo2-0-xrd.slb.sfdc.net/dva/sam/madkub:102-5201f60ec3458206b47cc7c1b03944e2e47aa9c7",
      "namespaceHostSubList": [
        "cloudatlas"
      ],
      "slbUseIlbInGkeEnv": true,
      "volPermissionInitContainerImage": "ops0-artifactrepo2-0-xrd.slb.sfdc.net/docker-gcp/dva/sam/hypersam:2601-1bbc5de4786678763a4e8a71681ee42ada887c76"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    pcn: deploy
    sam.data.sfdc.net/owner: sam
  name: samapp-controller
  namespace: sam-system
