apiVersion: v1
data:
  samcontroldeployer.json: |-
    {
      "app-key-ttl-duration": "12h",
      "delete-orphans": false,
      "disable-security-check": true,
      "dry-run": false,
      "email": false,
      "email-delay": 0,
      "etcd-override": "http://0.0.0.0:2379",
      "funnelEndpoint": "funnel.ajnalocal1.vip.core.test.us-central1.gcp.sfdc.net:443",
      "max-resource-time": "20m",
      "poll-delay": 30000000000,
      "recipient": "sam@salesforce.com",
      "resource-cooldown": 15000000000,
      "resource-progression-timeout": 120000000000,
      "resources-to-skip": [
        "sdn-secret.yaml"
      ],
      "sender": "sam@salesforce.com",
      "smtp-server": "fakeSmtpServer",
      "tnrp-endpoint": "https://ops0-artifactrepo2-0-xrd.slb.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    pcn: deploy
    sam.data.sfdc.net/owner: sam
  name: samcontrol-deployer
  namespace: sam-system
