apiVersion: v1
data:
  ci-namespaces.json: |-
    {
      "namespacesToTeam": {
        "ci-atf": "atf",
        "ci-atf-dev": "atf",
        "ci-atf-mirror": "atf",
        "ci-atf-mit": "atf",
        "ci-atf-mit-dev": "atf",
        "ci-atf-mit-mirror": "atf",
        "ci-cast": "cast",
        "ci-ccait": "ccait",
        "ci-cloudatlas": "cloudatlas",
        "ci-core-on-sam": "core-on-sam",
        "ci-emailinfra": "emailinfra",
        "ci-gateway": "gateway",
        "ci-global-identity": "global-identity",
        "ci-ice-pd": "ice-pd",
        "ci-iot": "iot",
        "ci-retail-cre": "retail-cre",
        "ci-retail-dfs": "retail-dfs",
        "ci-retail-mds": "retail-mds",
        "ci-retail-rsui": "retail-rsui",
        "ci-search-scale-safely": "search-scale-safely",
        "ci-user-mmittelstadt": "user-mmittelstadt",
        "ci-user-sample": "user-sample",
        "ci-user-vpod": "user-vpod",
        "csc-sam": "csc-sam"
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: ci-namespaces
  namespace: sam-system
