apiVersion: v1
data:
  samcontroldeployer.json: |-
    {
      "ca-file": "/etc/pki_service/ca/cabundle.pem",
      "cert-file": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "delete-orphans": true,
      "disable-security-check": true,
      "dry-run": false,
      "email": true,
      "email-delay": 0,
      "funnelEndpoint": "ajna0-funnel1-0-prd.data.sfdc.net:80",
      "key-file": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "max-resource-time": "5m",
      "poll-delay": "30s",
      "recipient": "sam@salesforce.com,slb@salesforce.com",
      "resource-cooldown": "15s",
      "resource-progression-timeout": "2m",
      "resources-to-skip": [
        "sdn-secret.yaml"
      ],
      "sender": "sam@salesforce.com",
      "smtp-server": "rd1-mta1-4-sfm.ops.sfdc.net:25",
      "tnrp-endpoint": "https://ops0-piperepo1-0-prd.data.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: samcontrol-deployer
  namespace: sam-system
