apiVersion: v1
data:
  hosts.json: |-
    {
      "hosts": [
        {
          "bomrolename": "samdev_compute",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevcompute1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n32-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdev_compute",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevcompute1-2-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "c02-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdev_compute",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevcompute2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "n31-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdev_kube_api",
          "controlestate": "prd-samdev",
          "devicerole": "samkubeapi",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevkubeapi1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "v34-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdev_kube_api",
          "controlestate": "prd-samdev",
          "devicerole": "samkubeapi",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevkubeapi2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "m35-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdev_kube_api",
          "controlestate": "prd-samdev",
          "devicerole": "samkubeapi",
          "estate": "prd-samdev",
          "hostname": "shared0-samdevkubeapi3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "m41-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdevpool",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdevpool",
          "hostname": "shared0-samdevpool1-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "h21-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdevpool",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdevpool",
          "hostname": "shared0-samdevpool2-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "h11-45",
          "superpod": "none"
        },
        {
          "bomrolename": "samdevpool",
          "controlestate": "prd-samdev",
          "devicerole": "samcompute",
          "estate": "prd-samdevpool",
          "hostname": "shared0-samdevpool3-1-prd.eng.sfdc.net",
          "kingdom": "prd",
          "pod": "none",
          "rack": "f35-45",
          "superpod": "none"
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    sam.data.sfdc.net/owner: sam
  name: sfdchosts
  namespace: sam-system
