apiVersion: v1
data:
  tempmanifestwatcher.json: |-
    {
      "caFile": "/etc/pki_service/ca/cabundle.pem",
      "certFile": "/etc/pki_service/platform/platform-client/certificates/platform-client.pem",
      "crdDeletionEnabled": true,
      "crdEnabled": true,
      "disableCertsCheck": true,
      "endpointRepoName": null,
      "keyFile": "/etc/pki_service/platform/platform-client/keys/platform-client-key.pem",
      "lockName": "/locks/tempmanifestwatcher",
      "tlsEnabled": true,
      "tnrpArchiveEndpoint": "https://ops0-piperepo1-0-prd.data.sfdc.net/tnrp/content_repo/0/archive"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: temp-manifest-watcher
  namespace: sam-system
