apiVersion: v1
data:
  datacenter: mvp
  region: us-west-1
  substrate: gcp
  zone: a
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    pcn: deploy
  name: rsyslog-metadata-cm
  namespace: sam-system
