apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: prometheus-scraper
  name: prometheus-scraper
  namespace: flowsnake
spec:
  minReadySeconds: 15
  replicas: 2
  selector:
    matchLabels:
      service: prometheus-scraper
  template:
    metadata:
      annotations:
        madkub.sam.sfdc.net/allcerts: '{"certreqs": [{"cert-type": "client", "kingdom":
          "prd", "name": "prometheusscrapercerts", "role": "flowsnake_metrics"}]}'
      labels:
        apptype: monitoring
        flowsnakeOwner: dva-transform
        flowsnakeRole: PrometheusScraper
        name: prometheus-scraper
        service: prometheus-scraper
    spec:
      containers:
      - args:
        - --config.file=/etc/config/prometheus.json
        - --storage.tsdb.path=/prometheus-storage
        - --web.external-url=http://localhost/
        - --web.enable-lifecycle
        image: minikube/prome_for_k8s:37
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
        name: prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /prometheus-storage
          name: prometheus-storage-volume
        - mountPath: /etc/config
          name: prometheus-server-conf
        - mountPath: /etc/pki_service
          name: certs-volume
        - mountPath: /certs
          name: datacerts
      - args:
        - --serviceName=flowsnake
        - --subserviceName=NONE
        - --tagDefault=superpod:NONE
        - --tagDefault=datacenter:prd
        - --tagDefault=estate:prd-minikube-big-flowsnake
        - --batchSize=512
        - --funnelUrl=http://ajna0-funnel1-0-prd.data.sfdc.net:80
        image: minikube/funnel_writer:37
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
        name: funnel-writer
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /prometheus-storage
          name: prometheus-storage-volume
        - mountPath: /certs
          name: datacerts
      - args:
        - /sam/madkub-client
        - --madkub-endpoint
        - https://madkubserver:32007
        - --maddog-endpoint
        - https://maddog-onebox:8443
        - --maddog-server-ca
        - /maddog-onebox/ca/security-ca.pem
        - --madkub-server-ca
        - /maddog-onebox/ca/ca.pem
        - --token-folder
        - /tokens
        - --kingdom
        - prd
        - --superpod
        - None
        - --estate
        - prd-minikube-big-flowsnake
        - --refresher
        - --run-init-for-refresher-mode
        - --cert-folders
        - prometheusscrapercerts:/certs
        - --ca-folder
        - /maddog-onebox/ca
        - --log-level
        - "7"
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: minikube/madkub:minikube
        name: sam-madkub-integration-refresher
        resources: {}
        volumeMounts:
        - mountPath: /certs
          name: datacerts
        - mountPath: /tokens
          name: tokens
        - mountPath: /maddog-onebox
          name: maddog-onebox-certs
      initContainers:
      - args:
        - /sam/madkub-client
        - --madkub-endpoint
        - https://madkubserver:32007
        - --maddog-endpoint
        - https://maddog-onebox:8443
        - --maddog-server-ca
        - /maddog-onebox/ca/security-ca.pem
        - --madkub-server-ca
        - /maddog-onebox/ca/ca.pem
        - --token-folder
        - /tokens
        - --kingdom
        - prd
        - --superpod
        - None
        - --estate
        - prd-minikube-big-flowsnake
        - --cert-folders
        - prometheusscrapercerts:/certs
        - --ca-folder
        - /maddog-onebox/ca
        - --log-level
        - "7"
        env:
        - name: MADKUB_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MADKUB_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MADKUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: minikube/madkub:minikube
        name: sam-madkub-integration-init
        resources: {}
        volumeMounts:
        - mountPath: /certs
          name: datacerts
        - mountPath: /tokens
          name: tokens
        - mountPath: /maddog-onebox
          name: maddog-onebox-certs
      restartPolicy: Always
      serviceAccountName: prometheus-scraper
      volumes:
      - configMap:
          name: prometheus-server-conf
        name: prometheus-server-conf
      - emptyDir:
          medium: Memory
        name: prometheus-storage-volume
      - hostPath:
          path: /etc/pki_service
        name: certs-volume
      - emptyDir:
          medium: Memory
        name: datacerts
      - emptyDir:
          medium: Memory
        name: tokens
